<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Trax.Scheduler</AssemblyName>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Trax.Effect" />
    <PackageReference Include="Trax.Mediator" />
    <PackageReference Include="Trax.Effect.Data" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Cronos" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Trax.Runner.Lambda" />
    <InternalsVisibleTo Include="Trax.Scheduler.Hangfire" />
    <InternalsVisibleTo Include="Trax.Scheduler.Sqs" />
    <InternalsVisibleTo Include="Trax.Scheduler.Tests" />
    <InternalsVisibleTo Include="Trax.Scheduler.Tests.Integration" />
    <InternalsVisibleTo Include="Trax.Scheduler.Tests.Stress" />
    <InternalsVisibleTo Include="Trax.Scheduler.Tests.Sqlite.Integration" />
  </ItemGroup>
</Project>
